name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Python files
        run: |
          pip install flake8
          #Ignore some common style warnings during the early development stage
          flake8 backend --ignore E302,W291,W293,E211,E261,E225,E231,E303,E305,E265,W292

      - name: Run basic syntax test
        run: |
          python -m py_compile backend/*.py
